<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f8efd561-8056-4b52-b326-5a4dfa7df24d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	//Pulsador AT %I*: BOOL;
	//Lampara AT %Q*: BOOL;
	
	Selector_modo_manual AT %I*: BOOL;
	
	test_pieza: FB_Bloque;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF NOT Selector_modo_manual THEN
test_pieza();
END_IF]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="29" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="41" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>