<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{56f4075e-4895-4e88-bf82-4d98b9642bb1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	//Pulsador AT %I*: BOOL;
	//Lampara AT %Q*: BOOL;
	
	bloque = FB_Bloque;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[FB_Bloque();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="29" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>