<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c478c710-59ab-4b65-8697-a4d1a270272c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    Estacion: FB_Estacion;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Estacion();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>