<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b59a8d37-4f5d-49aa-ba06-e026524f70e1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    Estacion: FB_Estacion;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Estacion();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>