<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{e4a90306-f409-4a7b-93ef-0ed7f90ceaa4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	//Pulsador AT %I*: BOOL;
	//Lampara AT %Q*: BOOL;
	
	Estacion: FB_Estacion;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Estacion();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="29" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>