<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{00882189-f86f-4cea-921e-f5fd8e9f7b86}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	//Pulsador AT %I*: BOOL;
	//Lampara AT %Q*: BOOL;
	
	Estacion: FB_Estacion;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Estacion();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="29" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>