<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Coordinador_SFC" Id="{60d81b79-472a-43ce-b469-a176d1d4b3ba}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Coordinador_SFC
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Coordinador_SFC">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>