<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_AlimentadorVerificadorDesplazador_SFC" Id="{7f4de525-f50b-41f6-a3a5-2636ab1bf832}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AlimentadorVerificadorDesplazador_SFC
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AlimentadorVerificadorDesplazador_SFC">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>