<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Descargador_SFC" Id="{cd8ae9d2-ce0b-47f0-9c5c-ad9300c2d5f3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AlimentadorVerificadorDesplazador_SFC
VAR_INPUT
	// SFC-Flags
	SFCPause: BOOL;
	SFCReset: BOOL;
	
	//Indicadores de sincronizacion
	Ack: BOOL:= TRUE;
	Execute: BOOL;
	
	//Entradas
	
	Alimentador_delante: BOOL; //Bajo el verificador
	Alimentador_detras: BOOL;
	Verificador_abajo: BOOL;
	Desplazador_delante: BOOL;
	
END_VAR
VAR_OUTPUT
	//indicadores de sincronizacion
	Done: BOOL;
	Ready: BOOL;

	//Salidas
	Alimentador_adelante: BOOL;
	Verificador_baja: BOOL;
	Desplazador_adelante: BOOL;

END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Descargador_SFC">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>