<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TransferirPale_SFC" Id="{808a1294-3b34-461d-81d0-34653480cb1f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TransferirPale_SFC
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TransferirPale_SFC">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>